### ISSUE TITLE
put how to make the doc in README

### ISSUE THREAD

**Issue by jgirardet** [gsemet/python-module-cookiecutter#1]
Hello,
Amazing cc with pipenv and pytest.

I read the pbr doc but I can't do it with your package, 

Please could you explain it to me.

Thanks lot for your work
Jimmy

**Comment by gsemet** [comment]
you mean `make docs` ?

**Comment by jgirardet** [comment]
no "docs" in the Makefile

**Comment by gsemet** [comment]
Ah yes, i have no updated this cookie cutter. I will discard it, no more relevant. You can look at my package « cfgtree » in my github for a python library that provides « make docs »

**Comment by jgirardet** [comment]
ok thank you
